import { InMemoryDbService } from 'angular2-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let ents = [
      {id: 1, platform: 'ERP', server: 'https://ecludev-test.fs.us2.oraclecloud.com', integrationType: 'FBDI', integrationName: 'Import Journals', fileName: 'journals1.zip', status: 'New'},
      {id: 2, platform: 'ERP', server: 'https://ecludev-test.fs.us2.oraclecloud.com', integrationType: 'FBDI', integrationName: 'Import Suppliers', fileName: 'suppliers.zip', status: 'New'},
      {id: 3, platform: 'ERP', server: 'https://ecludev-test.fs.us2.oraclecloud.com', integrationType: 'FBDI', integrationName: 'Import Journals', fileName: 'journalsmfh.zip', status: 'New'},
      {id: 4, platform: 'ERP', server: 'https://ecludev-test.fs.us2.oraclecloud.com', integrationType: 'FBDI', integrationName: 'Import Journals', fileName: 'journalsmfh2.zip', status: 'Error'},
      {id: 5, platform: 'ERP', server: 'https://ecludev-test.fs.us2.oraclecloud.com', integrationType: 'FBDI', integrationName: 'Import Journals', fileName: 'journalsmfh2.zip', status: 'Success'},
       {id: 5	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 6	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh3.zip'	,	 status: 'Warning'}	,
 {id: 7	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh3.zip'	,	 status: 'Warning'}	,
 {id: 8	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh3.zip'	,	 status: 'Warning'}	,
 {id: 9	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh3.zip'	,	 status: 'Warning'}	,
 {id: 10	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh3.zip'	,	 status: 'Warning'}	,
 {id: 11	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Warning'}	,
 {id: 12	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 13	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 14	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 15	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 16	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 17	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 18	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 19	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Recs.zip'	,	 status: 'Success'}	,
 {id: 20	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Recs.zip'	,	 status: 'Success'}	,
 {id: 21	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Recs.zip'	,	 status: 'Warning'}	,
 {id: 22	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Warning'}	,
 {id: 23	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Stuff.zip'	,	 status: 'Warning'}	,
 {id: 24	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Stuff.zip'	,	 status: 'Warning'}	,
 {id: 25	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Suppliers'	,	 fileName: 'Stuff.zip'	,	 status: 'Warning'}	,
 {id: 26	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'Stuff.zip'	,	 status: 'Success'}	,
 {id: 27	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'Stuff.zip'	,	 status: 'Error'}	,
 {id: 28	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'Stuff.zip'	,	 status: 'Error'}	,
 {id: 29	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'Stuff.zip'	,	 status: 'Error'}];	
 /*
 {id: 30	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Stuff.zip'	,	 status: 'Error'}	,
 {id: 31	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'Stuff.zip'	,	 status: 'Error'}	,
 {id: 32	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 33	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 34	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 35	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 36	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 37	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 38	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 39	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 40	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 41	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 42	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 43	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 44	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 45	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 46	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 47	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 48	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 49	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 50	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Banks'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 51	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 52	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 53	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 54	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 55	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 56	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 57	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 58	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 59	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 60	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 61	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 62	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 63	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 64	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 65	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 66	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 67	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 68	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 69	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 70	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 71	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Error'}	,
 {id: 72	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 73	,	 platform: 'HCM'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 74	,	 platform: 'HCM'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 75	,	 platform: 'HCM'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 76	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 77	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 78	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 79	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 80	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 81	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 82	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 83	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 84	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 85	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 86	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 87	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 88	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 89	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 90	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 91	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 92	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Supplier Sites'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 93	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 94	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 95	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 96	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 97	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 98	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 99	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 100	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 101	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 102	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 103	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}	,
 {id: 104	,	 platform: 'ERP'	,	 server: 'https://ecludev-test.fs.us2.oraclecloud.com'	,	 integrationType: 'FBDI'	,	 integrationName: 'Import Journals'	,	 fileName: 'journalsmfh2.zip'	,	 status: 'Success'}]; 
*/
    
    return {ents};
  }
}

/*
platform : string;
    server: string;
    integrationType: string;
    integrationName: string;
    fileName: string;
    status: string;
*/